services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "80:80"
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
    #   - ./etc/:/etc/letsencrypt/ ATTIVARE PER LA GENERAZIONE DEI CERTIFICATI
    
  backend:
      build:
        context: .
        dockerfile: Dockerfile
        target: backend-stage
      container_name: backend
      ports:
        - "3000:3000"
      volumes:
        - ./server/data/teams.json:/hackathon25/server/data/teams.json
        - ./server/data/students.json:/hackathon25/server/data/students.json
      depends_on:
        - mongodb
      environment:
          - MONGODB_URI=mongodb://mongodb:27017/hackathon
  
  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - /server/db :/data/db
        - ./mongodb/init/:/docker-entrypoint-initdb.d/
  
  certbot:
    image: certbot/certbot:latest
    profiles:
      - certgen  #Per edeguire certbot specificare --profile certgen
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw